global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']

  - job_name: 'document-service'
    static_configs:
      - targets: ['document-service:8000']

  - job_name: 'ocr-service'
    static_configs:
      - targets: ['ocr-service:8000']

  - job_name: 'nlp-service'
    static_configs:
      - targets: ['nlp-service:8000']

  - job_name: 'form-service'
    static_configs:
      - targets: ['form-service:8000']
